### ISSUE TITLE
AT-Bus module not loading

### ISSUE THREAD

**Issue by KiaSohc** [Estanz0/MMM-AT-Bus#6] opened 2022-11-12 03:32 UTC
Hi there. I have been trying to use the AT-Bus module but I could not make it work. I can only so far see the "Finding Bus Arrival Times..." text being displayed on the screen but that's it.

I have already generated and updated a number of API Keys but it still does not work. Are you able to help please? Is there something I am missing?

Below is a snippet of my config.

		{
		    disabled: false,
		    module: 'MMM-AT-Bus',
			header: "Auckland Transport",
			position: 'top_right',	
			config: {
			    bus: '755', 
			    stopCode: '7661', 
			    key: 'key'  // I have already used different API keys for this from https://dev-portal.at.govt.nz/
			}
		},

Many Thanks!

**Comment by byronxlg** [comment] 2022-11-20 05:11
Hi there,
Thanks for raising this issue.

I believe the issue was caused by the forwardLimit, which filters out buses arriving after this limit, was initially set too low (20 minutes).

I've updated the default limit to an hour and provided info in the readme for setting this parameter in the config.js.

Let me know if this solves your issue.

Thanks

**Comment by KiaSohc** [comment] 2022-12-02 12:45
Hey, thanks for this. I have already updated my config to contain the forwardLimit but still unable to make it work. :( I have also tried reinstalling MMM-AT-Bus but the same is happening where I can only see the "Finding Bus Arrival Times..." text. I also tried increasing the forwardLlimit value but still unsuccessful. See attached snapshot.

![image](https://user-images.githubusercontent.com/16767192/205295866-5252aa88-8e15-4e18-8940-530f1a3f3b56.png)

**Comment by KiaSohc** [comment] 2023-01-11 13:09
Hi there,

Happy New Year! Thanks for getting back to me on this. It took me quite a
while to get back working on it unfortunately.

I was again trying but still could not make the bus schedule show. All I
can see is the 'Finding Bus Arrival Times..' texts.

[image: image.png]

I again tried to reinstall the module but still could not make it work.

Is there something I should be doing differently? Below is a sample of the
config I am using

{
   disabled: false,
   module: 'MMM-AT-Bus',

header: "Auckland Transport",
position: 'top_right',
config: {
   bus: 'xxx',
   stopCode: 'xxx',
   forwardLimit: '3600',
   key: 'xxx'  // AT Developer key (https://dev-portal.at.govt.nz/)
}

},

Could it be the API key that I am using?

I would really like to make this work as this would be very handy
knowing the bus sched.

Many thanks!

Kind regards,
Raymond

**Comment by KiaSohc** [comment] 2023-01-31 12:12
Hi there, just to check with you. Is it correct that I have subscribed to the Public Transport Dev from AT Developer Portal? So far looking at my stats, all of my calls have been blocked and not a single successful one. Could it be an issue with my account? Also, do I need to submit an application for my project in the AT Developer Portal? The one I submitted has a status of "Submitted". Sorry, I am just trying to understand where I got it wrong. Thanks!

**Comment by byronxlg** [comment] 2023-02-02 12:10
Hi there,

This is the correct subscription needed ([https://dev-portal.at.govt.nz/products/](https://dev-portal.at.govt.nz/products/)):

![Screen Shot 2023-02-03 at 1 06 01 AM](https://user-images.githubusercontent.com/68315031/216320438-2320a783-881c-4bfc-89f4-d970d9023519.jpg)

This can be tested using the following command:
`curl -v -X GET "https://api.at.govt.nz/v2/gtfs/stops/stopCode/7661" -H "Ocp-Apim-Subscription-Key: {API_KEY}"`

With the expected response being:
`{"status":"OK","response":[{"stop_id":"7661-20230201141150_v104.10","stop_name":"St Stephens Avenue/Canterbury Place","stop_desc":null,"stop_lat":-36.85401,"stop_lon":174.78826,"zone_id":"merged_12","stop_url":null,"stop_code":"7661","stop_street":null,"stop_city":null,"stop_region":null,"stop_postcode":null,"stop_country":null,"location_type":0,"parent_station":"11495-20230201141150_v104.10","stop_timezone":null,"wheelchair_boarding":null,"direction":null,"position":null,"the_geom":"0101000020E6100000D717096D39D965407E3A1E33506D42C0"}],"error":null}`

Hope this helps!

**Comment by KiaSohc** [comment] 2023-02-03 13:26
HI there,

Thanks for this. Yes, I have the same subscription.

When I tried running the command, I get the following response.

{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }`

My Key is working if I try to run it from the AT Portal...
![image](https://user-images.githubusercontent.com/16767192/216614689-70194e93-1353-4a4b-bda7-72ce2c96cc50.png)

**Comment by byronxlg** [comment] 2023-02-05 23:59
Can you confirm you are using the key for the 'Developers' subsription, and not the key for 'Public Transport Dev'? 

![Screen Shot 2023-02-06 at 12 56 33 PM](https://user-images.githubusercontent.com/68315031/216853430-27f311eb-a63d-4165-b293-c91fa9bf51d1.jpg)

**Comment by KiaSohc** [comment] 2023-02-06 08:58
Hi, this is the only one I have avaiable.

![image](https://user-images.githubusercontent.com/16767192/216927911-83e8cb50-6cf2-4d2a-a435-c9728b27223a.png)

How do I apply for a Developer subscription? I am unable to find it. The only options visible to me are the ones below.

![image](https://user-images.githubusercontent.com/16767192/216928400-63deaa93-1fd3-454c-8b05-014769a11e57.png)

My apologies for the hassle.

**Comment by KiaSohc** [comment] 2023-02-06 09:19
Just this subscription basically...

![image](https://user-images.githubusercontent.com/16767192/216933229-9bc95fef-f4ce-4bf2-96e5-a50ed8fa6429.png)

**Comment by byronxlg** [comment] 2023-02-08 10:45
Ah ok, it looks like the Developer subscription is no longer available. I'll update the module to use the Public Transport Dev subscription in the next few days.

**Comment by KiaSohc** [comment] 2023-02-10 12:07
Thanks! Can't wait to make it work on my mirror! :)

**Comment by KiaSohc** [comment] 2023-09-01 13:04
Hi there. Hope all is well with you. Just checking if you have an updated version for your module? Thanks! :)

**Closed as completed** 2024-02-10 09:31 UTC
Labels: bug

**Comment by KiaSohc** [comment] 2024-02-10 10:04
Hey! Was working on my MM and saw your update... it's now working! Wooohoooo! Thanks heaps! :)

**Comment by KiaSohc** [comment] 2024-02-12 03:48
Hi, just want to let you know that the module stopped working yesterday. It was working perfectly fine as mentioned the other day but has now stopped showing the info... it's now just showing the "Finding Bus Arrival Times..." text. Have not done anything with other modules. The only modules I have running are MMM-Globe, MMM-Countdown, MMM-Earth, MMM-Flipclock, MMM-GoogleCalendar, MMM-MonthlyCalendar, MMM-MyGarbage, MMM-SystemStats, MMM-NewsFeedticker and MMM-WifiPassword. Just wondering if you have encountered something from your end? No rush... thanks! :)

**Comment by KiaSohc** [comment] 2024-02-15 04:45
Hey, I think I know what the main issue here is - the issue is affecting a specific Bus No. on a specific Bus Route. The issue is so far affecting Bus 120 coming from Stop 5841 Henderson and ends at Stop 4221 in Constellation. Any other Bus (i.e. 112 and 114) on that same route will work for your module. Hope this helps.
